\documentclass[final]{beamer}
\graphicspath{{Images/}}

%Packages
\usepackage{wrapfig}
\usepackage{tikz,amsmath,amssymb, etoolbox, expl3, mathtools, pgfkeys, pgfopts, xparse, xstring,graphicx,comment}
\usepackage{dynkin-diagrams}
\usepackage[T1]{fontenc}
\usepackage[size=custom,width=120,height=90,scale=1.0]{beamerposter}
\usepackage{lmodern}
\usetheme{gemini}
\usecolortheme{gemini}
\usepackage{booktabs}
\usepackage{pgfplots}
\pgfplotsset{compat=1.17}

%Style
\pgfkeys{/Dynkin diagram,
edge length=1.5cm,
mark=o,
root radius=0.2cm,
fold radius=1cm,
indefinite edge/.style={
draw=black,
fill=white,
thin,
densely dashed}}


%Header/Footer
\title{The Classification of Lie Algebras}
\author{Leo Jones}
\institute{Imperial College London}
\footercontent{\raggedleft{link to presentation: https://imperial.cloud.panopto.eu/Panopto/Pages/Viewer.aspx?id=3569143d-69ae-4da6-832d-aeb700daf013}}
\logoleft{\includegraphics[height=5cm]{IMP_ML_W_N_CLEAR-SPACE.png}}

%Blocks
\newlength{\sepwidth}
\newlength{\colwidth}
\setlength{\sepwidth}{0.025\paperwidth}
\setlength{\colwidth}{0.3\paperwidth}
\newcommand{\separatorcolumn}{\begin{column}{\sepwidth}\end{column}}

\usepackage{caption}
\captionsetup[figure]{labelformat=empty}

\begin{document}
\begin{frame}[t]
\begin{columns}[t]
\begin{column}{\colwidth}

\newcounter{boxlblcounter}  
\newcommand{\makeboxlabel}[1]{\fbox{L#1}\hfill}
\newcommand{\makeboxlabelR}[1]{\fbox{R#1}\hfill}
\newenvironment{boxlabel}
  {\begin{list}
    {\arabic{boxlblcounter}}
    {\usecounter{boxlblcounter}
     \setlength{\labelwidth}{3em}
     \setlength{\labelsep}{0em}
     \setlength{\itemsep}{2pt}
     \setlength{\leftmargin}{3.5cm}
     \setlength{\rightmargin}{2cm}
     \setlength{\itemindent}{0em} 
     \let\makelabel=\makeboxlabel
    }
  }
{\end{list}}
\newenvironment{boxlabelR}
  {\begin{list}
    {\arabic{boxlblcounter}}
    {\usecounter{boxlblcounter}
     \setlength{\labelwidth}{3em}
     \setlength{\labelsep}{0em}
     \setlength{\itemsep}{2pt}
     \setlength{\leftmargin}{3.5cm}
     \setlength{\rightmargin}{2cm}
     \setlength{\itemindent}{0em} 
     \let\makelabel=\makeboxlabelR
    }
  }
{\end{list}}

\begin{block}{Lie Algebras}
A \textbf{Lie algebra} consists of a vector space ($L$) and an operation called the Lie bracket, which we will denote $[-,-]$, that satisfies the following axioms [3]:
\begin{boxlabel}
\item $[-,-]$ is bilinear;
\item $[x,x]=0 \hspace{1cm} \forall x \in L$
\item $[x,[y,z]]+[y,[z,x]]+[z,[x,y]]=0$ \hspace{2cm} (the \textbf{Jacobi identity})
\end{boxlabel}
This operation is generally not associative nor commutative. Through a \emph{Levi decomposition}, we can express an arbitrary Lie algebra as a semi-direct sum of a solvable Lie algebra and a semisimple Lie algebra. We can understand an arbitrary solvable Lie algebra using \emph{Lie's theorem}. Classifying the semisimple Lie algebras takes a little more work.
\end{block}

\heading{Semisimple Lie Algebras}
A Lie algebra is \textbf{semisimple} if it contains no non-zero solvable ideals (you can think of ideals to Lie algebras like subgroups to a group). A semisimple Lie algebra can be expressed as a direct sum of \textbf{simple} Lie algebras (Lie algebras with no non-trivial ideals).

\textbf{Theorem [1]:} Every finite dimensional simple Lie algebra is isomorphic to one of the classical Lie algebras:
$$
sl(n,\mathbb{C})  \hspace{1cm} so(n,\mathbb{C})  \hspace{1cm}  sp(2n,\mathbb{C})
$$

with the exceptions: $e_{6},e_{7},e_{8},f_{4},g_{2}$

\begin{block}{Root Systems}
A subset $R$ of the Euclidean space $E$ (with inner product $(-,-)$) is a \textbf{root system} if it satisfies the axioms [1] (for $\alpha,\beta \in R$):

\begin{boxlabelR}
    \item $R$ is finite, spans $E$, and does not contain zero
    \item The only scalar multiples of $\alpha$ in $R$ are $\pm \alpha$
    \item The reflection $s_{\alpha}$ permutes the elements of $R$
    \item $\left\langle \alpha,\beta \right\rangle := \frac{2(\alpha,\beta)}{(\beta,\beta)} \in \mathbb{Z}$
\end{boxlabelR}

Every root system has a base. A subset $B$ of $R$ is a basis for the root system $R$ if:
\begin{itemize}
    \item $B$ is a vector space basis for $E$
    \item every $\beta \in R$ can be written as $\beta =\sum_{\alpha \in B}^{}k_{\alpha}\alpha$ with $k_{\alpha} \in \mathbb{Z}$, with same-signed, non-zero coefficients
\end{itemize}

\heading{Weyl Groups}
Denoted W(R). The group of invertible linear transformations of $E$ generated by the reflections $s_{\alpha}$ for $\alpha \in R$, where $s_{\alpha}$ denotes the reflection through the hyperplane perpendicular to $\alpha$ (this is visualised later in \textbf{Figure 2}).

Elements in the Weyl group can permute between base systems of $R$, ie.
\begin{equation}
\exists\; g \in W(R)\; |\; B'=\{g(\alpha): \alpha \in B\} [1]\tag{*}
\end{equation}
This will be useful later.
\end{block}

\begin{block}{Dynkin Diagrams}
We can represent the information about a root system in the form of a \textbf{Dynkin diagram}, $\Delta$. The vertices of $\Delta$ are labelled by the roots in the basis $B$ of $R$. Between two vertices $\alpha$ and $\beta$ we draw $d_{\alpha\beta}$ lines, where: 
\begin{equation} d_{\alpha\beta} := \left\langle \alpha,\beta \right\rangle\left\langle \beta,\alpha \right\rangle\in \{0,1,2,3\} \tag{using the Finiteness Lemma [1]}
\end{equation}
If $d_{\alpha\beta}>1$, (when $\alpha,\beta$ have different lengths and are not orthogonal), we draw an arrow from the longer root to the shorter one. As a result of (*), a Dynkin diagram of $R$ is independent from choice of base, and depends only on ordering - two root systems are isomorphic if their Dynkin diagrams are the same. We can also represent this information in a \emph{Cartan matrix}.

\textbf{Theorem [1]:} For an irreducible root system $R$, its Dynkin diagram falls into either one of four families (associated with the classical Lie algebras), or five exceptional diagrams (associated with all other semisimple Lie algebras):
\par
\begin{minipage}{\colwidth}
\begin{columns}[t]
\begin{column}{0.5\colwidth}
$A_{l}$ for l $\geq 1$: \dynkin A{} \quad $sl(l+1,\mathbb{C})$\par
$B_{l}$ for l $\geq 2$: \dynkin B{} \quad $so(2l+1,\mathbb{C})$\par
$C_{l}$ for l $\geq 3$: \dynkin C{} \quad $sp(2l,\mathbb{C})$\par
$D_{l}$ for l $\geq 4$: \dynkin D{} \quad $so(2l,\mathbb{C})$\par
\end{column}
\begin{column}{0.5\colwidth}
$E_{6}$: \dynkin E6 \par
$E_{7}$: \dynkin E7 \par
$E_{8}$: \dynkin E8 \par
$F_{4}$: \dynkin F4 \par
$G_{2}$: \dynkin G2 \par
\end{column}
\end{columns}
\end{minipage}
\begin{figure}
\raggedright{If two root systems have the same Dynkin diagram, they are isomorphic.}
\end{figure}
\end{block}
\end{column} 
\separatorcolumn

\begin{column}{\colwidth}
\begin{block}{Finding Root Systems}
\heading{2D cases [3]}
Let $E=\mathbb{R}^{2}$, with the Euclidean inner product (dot product). We want to find a root system, $R$. Since $R$ spans $E$, we can assume the existence of $\alpha,\beta \in R$. Let the angle between them be denoted $\theta$. 

\begin{minipage}{\colwidth}
\begin{columns}[t]
\begin{column}{0.6\colwidth}
 To satisfy the fourth axiom, we must limit the choices of $\theta$, as:
\vspace{1.5cm}
$$
    \left\| \alpha \right\|\left\| \beta \right\| \cos \theta = (\alpha,\beta)
$$
$$
    \therefore \left\langle \alpha,\beta \right\rangle = \frac{2(\alpha,\beta)}{(\beta,\beta)}= 2\frac{\left\| \alpha \right\|}{\left\| \beta \right\|}\cos\theta
$$
$$ \left\langle \alpha,\beta \right\rangle\left\langle  \beta,\alpha\right\rangle=4\cos^{2}\theta
$$
\end{column}
\begin{column}{0.4\colwidth}
\begin{center}
\begin{tabular}{c|c|c|c}
    $\left\langle \alpha,\beta \right\rangle$ & $\left\langle  \beta,\alpha\right\rangle$ & $\theta$&$\frac{\left\| \beta \right\|^{2}}{\left\| \alpha \right\|^{2}}$\\
    \hline
    0&0&$\pi/2$&undetermined\\
    1&1&$\pi/3$&1\\
    -1&-1&$2\pi/3$&1\\
    1&2&$\pi/4$&2\\
    -1&-2&$3\pi/4$&2\\
    1&3&$\pi/6$&3\\
    -1&-3&$5\pi/6$&3\\
\end{tabular}
\end{center}
\end{column}
\end{columns}
\end{minipage}

$\alpha\neq\pm\beta$ by the second axiom, and without loss of generality (to avoid duplication), we can assume $||\beta||>||\alpha||$. The possibilities for $\theta$ are therefore shown in the table above (with the final column as relative length).

By taking $\theta = \pi/3$, and using the third axiom, we find that $R$ contains six roots as shown in \textbf{Figure 1}.

It only remains to check the third axiom. It is clear that $R$ is closed under the reflections $s_{\alpha}$ for $\alpha \in R$ (that form the Weyl group), represented by the dashed lines in \textbf{Figure 2}. Note these symmetries are those of a symmetry group of an equilateral triangle, which this root system represents. 

\begin{figure}
\begin{tikzpicture}
    \foreach\ang in {0,60,120,...,360}{
     \draw[->,black,thick] (0,0) -- (\ang:2cm);
    }
    \draw[red,->](1,0) arc(0:60:1cm)node[pos=0.1,right,scale=0.5]{$\pi/3$};
    \node[anchor=west,scale=0.6] at (2,0) {$\alpha$};
    \node[anchor=east,scale=0.6] at (-2,0) {$-\alpha$};
    \node[anchor=south east,scale=0.6] at (-0.5,1.75) {$=\alpha + \beta$};
    \node[anchor=north west,scale=0.6] at (0.5,-1.75) {$\alpha - \beta$};
    \node[anchor=south west,scale=0.6] at (1,1.75) {$\beta$};
    \node[anchor=north east,scale=0.6] at (-1,-1.75) {$-\beta$};
    \node[anchor=north, scale=0.6] at (0,-3)  {\begin{tabular}{c}\textbf{Figure 1.}\\ Root system found using \\ $$\theta=\pi/3$$ \end{tabular}};
  \end{tikzpicture}
\begin{tikzpicture}
    \foreach\ang in {0,60,120,...,360}{
     \draw[->,black,thick] (0,0) -- (\ang:2cm);
    }
    \foreach\ang in {30,90,...,330}{
     \draw[black,dashed] (0,0) -- (\ang:2cm);
    }
    \coordinate (a) at (0,1);
    \coordinate (b) at (-0.866, -0.5);
    \coordinate (c) at (0.866,-0.5);
    \draw[dashed] (a)--(b)--(c)--(a);
    \node[anchor=west,scale=0.6] at (2,0) {$\alpha$};
    \node[anchor=east,scale=0.6] at (-2,0) {$-\alpha$};
    \node[anchor=south east,scale=0.6] at (-0.5,1.75) {$=\alpha + \beta$};
    \node[anchor=north west,scale=0.6] at (0.5,-1.75) {$\alpha - \beta$};
    \node[anchor=south west,scale=0.6] at (1,1.75) {$\beta$};
    \node[anchor=north east,scale=0.6] at (-1,-1.75) {$-\beta$};
    \node[anchor=north, scale=0.6] at (0,-3)  {\begin{tabular}{c}\textbf{Figure 2.}\\Previous root system,\\including the Weyl group symmetries \end{tabular}};
  \end{tikzpicture}
\begin{tikzpicture}
    \foreach\ang in {0,90,...,360}{
     \draw[->,black,thick] (0,0) -- (\ang:2cm);
    }
    \foreach\ang in {45,135,...,315}{
     \draw[->,black,thick] (0,0) -- (\ang:2.83cm);
    }
    \draw[red,->](1,0) arc(0:135:1cm)node[pos=0.1,right,scale=0.5]{$3\pi/4$};
    \node[anchor=west,scale=0.6] at (2,0) {$\alpha$};
    \node[anchor=east,scale=0.6] at (-2,0) {$-\alpha$};
    \node[anchor=south east,scale=0.6] at (-2,2) {$\beta$};
    \node[anchor=north west,scale=0.6] at (2,-2) {$-\beta$};
    \node[anchor=south west,scale=0.6] at (2,2) {$2\alpha+\beta$};
    \node[anchor=north east,scale=0.6] at (-2,-2) {$-2\alpha-\beta$};
    \node[anchor=south,scale=0.6] at (0,2) {$\alpha+\beta$};
    \node[anchor=north,scale=0.6] at (0,-2) {$-\alpha-\beta$};
    \node[anchor=north, scale=0.6] at (0,-3)  {\begin{tabular}{c}\textbf{Figure 3.}\\Root system found using\\ $$\theta=3\pi/4$$ \end{tabular}};
  \end{tikzpicture}
\begin{tikzpicture}
    \foreach\ang in {60,120,...,360}{
     \draw[->,black,thick] (0,0) -- (\ang:2cm);
    }
    \foreach\ang in {30,90,...,330}{
     \draw[->,black,thick] (0,0) -- (\ang:3cm);
    }
    \draw[red,->](1,0) arc(0:150:1cm)node[pos=0.1,right,scale=0.5]{$5\pi/6$};
    \node[anchor=west,scale=0.6] at (2,0) {$\alpha$};
    \node[anchor=east,scale=0.6] at (-2,0) {$-\alpha$};
    \node[anchor=south east,scale=0.6] at (-2.5,1.5) {$\beta$};
    \node[anchor=north west,scale=0.6] at (2.5,-1.5) {$-\beta$};
    \node[anchor=south east,scale=0.6] at (-0.5,1.75) {$\alpha + \beta$};
    \node[anchor=north west,scale=0.6] at (0.5,-1.75) {$-\alpha - \beta$};
    \node[anchor=south west,scale=0.6] at (0.5,1.75) {$2\alpha + \beta$};
    \node[anchor=north east,scale=0.6] at (-0.5,-1.75) {$-2\alpha - \beta$};
    \node[anchor=south,scale=0.6] at (0,3) {$3\alpha +2 \beta$};
    %\node[anchor=north,scale=0.6] at (0,-3) {$-3\alpha -2 \beta$};
    \node[anchor=south west,scale=0.6] at (2.5,1.5) {$3\alpha + \beta$};
    \node[anchor=north east,scale=0.6] at (-2.5,-1.5) {$-3\alpha - \beta$};
    \node[scale=0.6] at (1,3) {$G_{2}$};
    \node[anchor=north, scale=0.6] at (0,-3)  {\begin{tabular}{c}\textbf{Figure 4.}\\Root system found using\\ $$\theta=5\pi/6$$ \end{tabular}};
  \end{tikzpicture} 
\end{figure}

To construct the Dynkin diagram from this, we see that $\alpha$ and $\beta$ form a basis for the roots. We therefore have two nodes, connected by $(\left\langle \alpha,\beta \right\rangle\left\langle  \beta,\alpha\right\rangle=) 1$ line: \dynkin A2. This is the diagram $A_{2}$, for $sl(3,\mathbb{C})$.

If we instead take $\theta=3\pi/4$ (\textbf{Figure 3}), we get a root system of type $B_{2}$, for $so(5,\mathbb{C})$:\dynkin B2 (with the arrow from the longer root $\beta$, to the shorter root $\alpha$).
  
Finally, taking $\theta=5\pi/6$ (\textbf{Figure 4}), we get a root system of exceptional type $G_{2}$: \dynkin G2.
 
Note: taking $\theta=2\pi/3$ we get an equivalent $A_{2}$ system, taking $\theta=\pi/4$ we get an equivalent $B_{2}$ system, taking $\theta=\pi/6$ we get an equivalent $G_{2}$ system, and taking $\theta=\pi/2$ we get an $A_{1}\times A_{1}$ system.
\heading{The Remaining Systems}
Proof of the existence of root systems for the general case of the four families associated with the classical Lie algebras, as well as finding them for the other exceptional groups, can be done through root space decomposition and is left as further reading. Their root systems are multi-dimensional and therefore cannot be directly represented.
\end{block}
\begin{block}{Coxeter Plane Projections}
Through use of Coxeter planes, we can visualise multi-dimensional root systems.

We use the same notation as before, with a basis $B={\alpha_{1},\alpha_{2},...\alpha_{n}}$ of a root system $R \subset E$, where $s_{\alpha}$ represents the reflection in the hyperplane perpendicular to $\alpha$. 

We define a \textbf{Coxeter element} as the product of these reflections [2]:
$$  s_{c}=\prod_{\alpha\in B}^{}s_{\alpha}
$$
The Coxeter element depends on the choice and ordering of B however its order is always the same, as all $s_{c}$ are conjugate to each other through elements of the Weyl group. We can therefore define the \textbf{Coxeter number} as the minimal $h$ such that $s_{c}^{h}=1$. 

For any Coxeter element $s_{c}$, we have a unique \textbf{Coxeter plane}, on which $s_{c}$ acts by rotation of $2\pi/h$. It is a 2D space which we can write as:
$$ C=\mathbb{R}x+\mathbb{R}y;
$$
where $z=x+iy$ is the corresponding eigenvector to eigenvalue $e^{\frac{2\pi i}{h}}$, for $s_{c}$. In essence, we can use this to project higher dimensional root systems onto our 2D plane (as a way of visualising them), giving a shape with $h$-fold rotational symmetry [5]. 

A root $\alpha \in R$ is projected to a node with components: $\alpha_{x}=(\alpha,x)$ and $\alpha_{y}=(\alpha,y)$. We then draw lines to each nodes' nearest neighbours (when their distance is minimal) [2]. 
\end{block}
\end{column}
\separatorcolumn

\begin{column}{\colwidth}
\begin{block}{Coxeter Plane Projections (cont.)}
\begin{minipage}{\colwidth}
\begin{columns}[t]
\begin{column}{0.35\colwidth}
\begin{wrapfigure}{r}{0.35\colwidth}
\centering
\includegraphics[height=10cm]{G2_blackred.png}\par
\caption{\textbf{Figure 5. }Projection for $G_{2}$}
\includegraphics[height=10cm]{F4_blackred.png}\par
\caption{\textbf{Figure 6. }Projection for $F_{4}$ [4]}
\includegraphics[height=10cm]{E6_blackred.png}\par
\caption{\textbf{Figure 7. }Projection for $E_{6}$ [4]}
\includegraphics[height=10cm]{E7_blackred.png}\par
\caption{\textbf{Figure 8. }Projection for $E_{7}$ [4]}
\includegraphics[height=10cm]{E8_redblack.png}\par
\caption{\textbf{Figure 9. }Projection for $E_{8}$ [4]}
\end{wrapfigure}
\end{column}
\begin{column}{0.5\colwidth}

\pgfkeys{/Dynkin diagram,
edge length=0.75cm,
fold radius=1cm,
root radius=0.1cm,
indefinite edge/.style={
draw=black,
fill=white,
thin,
densely dashed}}

\heading{Coxeter plane projection of $G_{2}$}
$G_{2}$ is already in two dimensions, and we can see its Coxeter plane projection in \textbf{Figure 5}. Notice how the nodes correspond directly to its root system diagram, pictured in \textbf{Figure 4}. 

It has 12 root vectors, and its Weyl group is of order 12 - the Dihedral group $D_{6}$ [2]. It has a Coxeter number of 6. Recall its Dynkin diagram \dynkin G2

\vspace{1cm}
\heading{Coxeter plane projection of $F_{4}$}
$F_{4}$ has a four dimensional root system, with Coxeter number 12, and is shown projected onto its Coxeter plane in \textbf{Figure 6}.

It has 48 root vectors and its Weyl group is of order 1,152 - the symmetry group of the \emph{24-cell} [2]. Note you can spot the four vectors that form a basis for the projected root system, corresponding to the simple roots shown in its Dynkin diagram: \dynkin F4
\vspace{1cm}
\heading{Coxeter plane projection of $E_{6}$}
$E_{6}$, has a six dimensional root system, with Coxeter number 12, and is shown projected onto its Coxeter plane in \textbf{Figure 7}.

It has 72 root vectors and its Weyl group is of order 51,840 -  the automorphism group of the simple group of order 25920 [6]. We only see 48 points as two sets of 12 roots project over each other. Therefore we see four sets, not six, as we'd expect from the dimension and the Dynkin diagram \dynkin E6.

\vspace{1cm}
\heading{Coxeter plane projection of $E_{7}$}
$E_{7}$ has a Coxeter number 18, and is shown projected onto its Coxeter plane in \textbf{Figure 8}.

It has 126 root vectors and its Weyl group is of order 2,903,040 -  the direct product of the cyclic group of order 2 and the unique simple group of order 1,451,520 [6]. \dynkin E7

\vspace{1cm}
\heading{Coxeter plane projection of $E_{8}$}
$E_{8}$, has a Coxeter number 30, and is shown projected onto its Coxeter plane in \textbf{Figure 9}.

It has 240 root vectors and its Weyl group is of order 696,729,600. \dynkin E8

\vspace{1cm}
\heading{Other plane projections}
There exist projections for the four families associated with the classical Lie algebras (for a given $l$), but I do not have space to include these. See references for further reading.

\vspace{1cm}

\end{column}
\end{columns}
\end{minipage}
\end{block}

\begin{block}{References}
\nocite{*}
\footnotesize{\bibliographystyle{plain}\bibliography{poster}}
\end{block}
\end{column}


\end{columns}
\end{frame}
\end{document}
